### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by hafsahussein** [briancodex/community-website#10]
I am not sure if my issue is valuable😁 but I am curious about contributing to a public project and I see all the issues are already assigned, so if this is valuable I will try to make the website responsive.

**Comment by briancodex** [comment]
We will have to wait until everyone submits their code so I can add new sections. I have a few ideas in mind, but I'll wait until tomorrow to see who's submitted code and create new sections after

**Comment by hafsahussein** [comment]
Thanks man

**Comment by nifty-coder** [comment]
Can I please do this whenever the others submit their code? I am 13 years old and learned many things. So this would be a learning experience for me though I have built quite A few projects but never by collaborating!

**Comment by briancodex** [comment]
@nifty-coder once everyone submits the first part of their code, then I can add you to another section and you can either edit their current code or create your own section from scratch. I just have to wait and see what the others build first, so I can give you something to work on

**Comment by nifty-coder** [comment]
ok no issues

**Comment by briancodex** [comment]
@nifty-coder I just added a new issue where the hero section and content section overlaps. If you think you can fix that, let me know. Or else someone else can take it

**Comment by briancodex** [comment]
@hafsahussein you can work on making the content section #2 responsive. Someone just uploaded their code and it's the section right below the image sliders. I'll create a new custom issue just focusing on that, so if you want it just comment on the new issue I create
