### ISSUE TITLE
Changes making after hero section are not reflecting on the browsers.

### ISSUE THREAD

**Issue by ghost** [briancodex/community-website#13]
I have inserted footer in the files but no changes are reflected on browsers. When commented all the code of hero section then it works fine.
![Capture1](https://user-images.githubusercontent.com/73336171/102710859-5d913300-42db-11eb-8091-9a470e5621c1.PNG)
![Capture](https://user-images.githubusercontent.com/73336171/102710872-76014d80-42db-11eb-858c-e89185678a60.PNG)

**Comment by abhinavmaharana** [comment]
Can I fix this @briancodex

**Comment by ghost** [comment]
> Can I fix this @briancodex

What is the problem can you explain me. So that i'll avoid such bugs in my projects.

**Comment by abhinavmaharana** [comment]
@atul787  i have to check the whole code
as the image is not sufficient

**Comment by abhinavmaharana** [comment]
it must be some alignment error

**Comment by ghost** [comment]
> it must be some alignment error

How can I fix that because before fixing that problem I cannot work on my issue.

**Comment by abhinavmaharana** [comment]
okay i will update you soon by night

**Comment by briancodex** [comment]
yeah if anyone wants to hop on this issue and fix it, you're welcome to

**Comment by atul787** [comment]
> yeah if anyone wants to hop on this issue and fix it, you're welcome to
I have footer ready but can not able to add in website due to this issue.
Are everyone getting this issue or I am the only one.

**Comment by ghost** [comment]
I have footer ready but can't able to add it to website due to this issue.
Are everyone getting this issue or I am the only one.

**Comment by suyashagno3** [comment]
I am also getting the same issue.
I guess CSS file has some error.

**Comment by suyashagno3** [comment]
Okay I got it fixed.
Give your footer a class and make the footer fixed using CSS.
Try this:)

**Comment by briancodex** [comment]
@atul787 can you give me an update on the footer? there's a lot of people wanting to contribute, so I need to push the sections as soon as possible

**Comment by JuniorDugue** [comment]
i can lend a 2nd pair of eyes as well

**Comment by briancodex** [comment]
@JuniorDugue I added another issue where the hero section overlap with the content section. You could look at that one if no one has taken it

**Comment by suyashagno3** [comment]
I left a comment yesterday, Did someone checked?
I would like to contribute too  : )

**Comment by briancodex** [comment]
looks like this issue is fixed. I'll close it now, but if anything comes up, just create a new issue

**Comment by JuniorDugue** [comment]
i noticed it was fixed by the time i got to it, does anyone know what the issue was? (that way i can learn moving forward)
