### ISSUE TITLE
Host the website on Github Pages

### ISSUE THREAD

**Issue by captain-aman-11** [briancodex/community-website#15]
If the website is hosted on github pages, then new contributers can quickly look over the website and then have an idea if they can add some features or improvements in it. Also, changes will be reflected very soon after someone pushes their code to the repo.

**Comment by briancodex** [comment]
yeah, I can do that once people submit their code. Right now we only have the hero section, so it's basically empty. I just made this repo last night, so I'm still waiting for the others to finish up their sections, then I can host it
