### ISSUE TITLE
Make Content Section #2 Responsive

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#19]
Make the content section #2 responsive.

**Comment by nifty-coder** [comment]
Will do this, Brian! By when should this be done?

**Comment by nifty-coder** [comment]
I will complete this by tomorrow same time : 7 pm

**Comment by briancodex** [comment]
@nifty-coder sounds good! I'll assign you to this now

**Comment by nifty-coder** [comment]
Thanks

**Comment by hafsahussein** [comment]
ah! sorry I was offline from here

**Comment by nifty-coder** [comment]
Hey Brian!  Just wanted to check which form factors and devices we are targeting.  I have started working already on some standard things.

**Comment by nifty-coder** [comment]
For all phones made it to display each service in a single column.  For tablets and desktop, made it 3 columns (same as the original version but replaced flex with grid).  Submitted the pull request as well.
