### ISSUE TITLE
Create a navbar

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#2]
Create a navbar in the index.html file

**Comment by aryan-jha-18** [comment]
Hey Brian i would love to work on this issue☺️

**Comment by briancodex** [comment]
I assigned it to you

**Comment by hafsahussein** [comment]
Hi Brian can I contribute to this section?

**Comment by briancodex** [comment]
@hafsahussein there's already someone who commented before you. So, you'd have to wait until I create a new section

**Comment by briancodex** [comment]
@aryan-jha-18 so far only 1 person has pushed their code to the repo. I made a new update to the rules, so you'd need to submit your portion within a 24 hour period, or else someone else can take the issue and I will have to push whoever commits first. The reason for this change is because there is a lot of people interesting in contributing and I wouldn't want them to wait weeks just for a section to be uploaded

**Comment by aryan-jha-18** [comment]
I'm on it i'll push commit in few hours

**Comment by briancodex** [comment]
@aryan-jha-18 awesome! sounds good

**Comment by aryan-jha-18** [comment]
HEY Brian I have pushed commit i hope you pull it soon!

**Comment by briancodex** [comment]
there's no pr showing up? are you sure you did it properly?

**Comment by aryan-jha-18** [comment]
Did u receive it now?

**Comment by briancodex** [comment]
yeah I merged it. I'll close this issue now
