### ISSUE TITLE
Remove overflow-x scrollbar on website

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#24]
There's an overflow-x scrollbar that displays when you toggle the nav hamburger menu icon or when the hero image slider changes to the next slide. Anyone want to add an overflow-x: hidden on the website so the scroll bar disappears? Or you can refactor the other sections, so the overflow doesn't show, but I think it's because of the animations

**Comment by abhinavmaharana** [comment]
I can add it if you permit

**Comment by briancodex** [comment]
I made a new issue with y scrollbar showing if you wanted to fix that
