### ISSUE TITLE
Increase website speed by compressing images file size

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#25]
The current hero images file sizes are extremely big and is causing the website to lag/slow down. Does anyone want to compress the hero section images file size? 

You could also download smaller images and compress the files as well. Right now the current images are massive with a width and height of 6000x4000 for some. If you know a better way to increase the website speed, please let a comment below

**Comment by nohahassan64** [comment]
Can I work on this

**Comment by briancodex** [comment]
yeah I'll assign you to it now
