### ISSUE TITLE
Images aren't showing up on hero section slider

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#27]
I just published the website to github pages and noticed the images don't display on the hero section. https://briancodex.github.io/community-website/ If you'd like to fix this issue, be sure to comment below.

**Comment by abhinavmaharana** [comment]
hi i fixed it will working on the navbar and footer

**Comment by abhinavmaharana** [comment]
can you close this issue please as it is solved thank you. I am waiting for new issues
