### ISSUE TITLE
Create a Hero Section

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#3]
Create the hero section in the index.html file

**Comment by JuniorDugue** [comment]
hey brian, I'm interested in the hero section, I had a question, is there a specific art or theme direction? or it's up to us? wasn't sure what stock images to search for and etc

**Comment by briancodex** [comment]
it's up to you. Just make sure to use copyright free images, so ones from like pixabay, unsplash, pexels, undraw etc. and I assigned you to this btw!

**Comment by briancodex** [comment]
I went ahead and merged your code. I'll close this issue now
