### ISSUE TITLE
Hero section slider text overlaps and shows all sliders at once

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#32]
Right now the hero slider shows all sections at once and doesn't display just one at a time. Anyone want to refactor the hero slider HTML & CSS to make it only display one slider at a time? If there are images in the background, then I don't think you would see the text overlap, but this will cause bigger issues if you try to add new animations & additional content to the sliders 

<img width="1330" alt="Screen Shot 2020-12-21 at 12 12 52 AM" src="https://user-images.githubusercontent.com/62127078/102745434-96ec9180-4321-11eb-8f53-7c76393ef908.png">

**Comment by Abhisek-Ray99** [comment]
i want to working on this issue

**Comment by briancodex** [comment]
I'll assign it to you now. You probably can't see this issue right now since the images are covering it, but if you remove the images, then I think it will show up because of the way the css what created
