### ISSUE TITLE
Add Navbar Menu to each page

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#35]
Add the navbar menu to each page. Right now when you navigate to about, it's just a blank screen, so we need the nav menu to display on every page

**Comment by abhinavmaharana** [comment]
can i do this and send you the pull request

**Comment by abhinavmaharana** [comment]
I have added the navbar in each page

**Comment by suyashagno3** [comment]
@briancodex I wanted to ask that why there are 2 about, contact and work html files?
