### ISSUE TITLE
Add Footer to each page

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#36]
Add the footer to each page, so it displays at the bottom whenever you navigate to another page

**Comment by abhinavmaharana** [comment]
Can I do this

**Comment by abhinavmaharana** [comment]
I have completed the issue and added the footer in each page

**Comment by abhinavmaharana** [comment]
I was very excited to work on open source with you before assigning to me i completed the task . This will not happen again.

**Comment by briancodex** [comment]
I think I'll make a new update to the rules. So, if you're the first person to comment you will be able to work on the issue without me having to assign it to you. I think time difference it's too difficult to assign everyone instantly, so as long as nobody else commented, then I see no issue with you working on it
