### ISSUE TITLE
Add Content Section #1 below Hero Section

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#4]
Create the first section with content below the hero section. Here's a picture of the structure for the website and the section names

![Group 148](https://user-images.githubusercontent.com/62127078/102703928-0f2c5780-423b-11eb-8142-7df881079094.png)

**Comment by mirajshaikh** [comment]
Can I work on this

**Comment by briancodex** [comment]
yeah I just assigned you to it

**Comment by briancodex** [comment]
@mirajshaikh so far only 1 person has pushed their code to the repo. I made a new update to the rules, so you'd need to submit your portion within a 24 hour period, or else someone else can take the issue and I will have to push whoever commits first. The reason for this change is because there is a lot of people interesting in contributing and I wouldn't want them to wait weeks just for a section to be uploaded

**Comment by briancodex** [comment]
I need an update on your progress or else I'll have to create a new issue so someone can work on this

**Comment by mirajshaikh** [comment]
i started working on this
