### ISSUE TITLE
Vertical scrollbar appears when clicking hamburger menu

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#40]
Need to remove this scrollbar that appears when you click the hamburger menu icon

![Screen Shot 2020-12-21 at 10 09 48 AM](https://user-images.githubusercontent.com/62127078/102797140-e3ad8800-4374-11eb-868b-3e19fe99268a.png)

**Comment by abhinavmaharana** [comment]
i will try to remove it, if assigned to me

**Comment by briancodex** [comment]
I assigned you to it

**Comment by abhinavmaharana** [comment]
please check and give feedback thank you

**Comment by briancodex** [comment]
I merged it
