### ISSUE TITLE
Change href path for LOGO to navigate back to home page 

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#44]
Need the update the logo href page for every page on the website to navigate back to the home page.

**Comment by abhinavmaharana** [comment]
can i work on it

**Comment by briancodex** [comment]
you got it

**Comment by briancodex** [comment]
@abhinavmaharana have you finished this issue yet?

**Comment by abhinavmaharana** [comment]
it is already completed and it merged also
in site it it there
sorry i only fixed the home page sending another pr in 5 mins
