### ISSUE TITLE
Add Content Section #2 

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#5]
Create the second content section. This is labeled **_Content Section 2_**. Here's a picture of the website structure

![Group 148](https://user-images.githubusercontent.com/62127078/102703948-400c8c80-423b-11eb-8b5e-e7c3c71971fe.png)

**Comment by bkkcreative19** [comment]
I would love to do this section. What are you actually looking for in the section. Theme and content rise.

**Comment by briancodex** [comment]
it's up to you. I haven't received any code from the others yet, so I don't know what theme they are making. You'd just have to create something neutral I guess for now, and then after more people add their sections you can see what they did and update your code if you want.  I'll assign you to this one now

**Comment by briancodex** [comment]
@bkkcreative19 so far only 1 person has pushed their code to the repo. I made a new update to the rules, so you'd need to submit your portion within a 24 hour period, or else someone else can take the issue and I will have to push whoever commits first. The reason for this change is because there is a lot of people interesting in contributing and I wouldn't want them to wait weeks just for a section to be uploaded
