### ISSUE TITLE
Add Content Section #3

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#6]
Create the third content section. This is labeled **_Content Section 3_**. Here's a picture of the website structure

![Group 148](https://user-images.githubusercontent.com/62127078/102703948-400c8c80-423b-11eb-8b5e-e7c3c71971fe.png)

**Comment by mirajshaikh** [comment]
Give this to me please 🥺

**Comment by briancodex** [comment]
I assigned it to you

**Comment by briancodex** [comment]
@mirajshaikh so far only 1 person has pushed their code to the repo. I made a new update to the rules, so you'd need to submit your portion within a 24 hour period, or else someone else can take the issue and I will have to push whoever commits first. The reason for this change is because there is a lot of people interesting in contributing and I wouldn't want them to wait weeks just for a section to be uploaded

**Comment by mirajshaikh** [comment]
I'm started working on this project.

**Comment by briancodex** [comment]
when do you think you'll have it finished?
