### ISSUE TITLE
Decrease mobile menu animation to less than 1s

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#62]
make the mobile menu animation faster when you click on the hamburger menu icon. Right now it is too slow when it opens

**Comment by suyashagno3** [comment]
I would like to work on this.

**Comment by suyashagno3** [comment]
I have rectified it. Just waiting for your response:)

**Comment by briancodex** [comment]
you can submit your PR now

**Comment by suyashagno3** [comment]
Done.
