### ISSUE TITLE
Make Section 1 and Section 4 Responsive

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#65]
Need someone to make Section 1 and Section 4 Responsive. Whoever submits a pull request first will be accepted for this issue.

**Comment by nteinert2005** [comment]
I can do this. Can I get it done?

**Comment by briancodex** [comment]
@nteinert2005 you got it

**Comment by briancodex** [comment]
@nteinert2005 this has been completed by someone else, so I'll close it now
