### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#7]
Create a footer section

**Comment by ghost** [comment]
Hey brian I would Love to work on this. I never contributed on any project please help me understand open source by assigning this task to me.
Thanks

**Comment by briancodex** [comment]
I assigned it to you

**Comment by nohahassan64** [comment]
Can I work on this

**Comment by briancodex** [comment]
@nohahassan64 someone just finished this issue. I added new issues that you can work on. Feel free to check them out
