### ISSUE TITLE
Create Mobile Menu

### ISSUE THREAD

**Issue by briancodex** [briancodex/community-website#8]
Convert the Navbar into a mobile menu

**Comment by aryan-jha-18** [comment]
Hey Brian i would love to contribute to this mobile menu issue ☺️

**Comment by briancodex** [comment]
you got it!

**Comment by aryan-jha-18** [comment]
HEY Brian I have pushed commit i hope you pull it soon!

**Comment by briancodex** [comment]
where did you push it? I don't see any pr's?

**Comment by aryan-jha-18** [comment]
Did u receive a pr now?

**Comment by briancodex** [comment]
yeah I got it! closing this issue now
